kumuluzee:
  name: microservice-uploader
  version: 1.0.0
  env:
    name: dev
  datasources:
      - jndi-name: jdbc/uploaderDS
        connection-url: jdbc:postgresql://192.168.99.100:5433/streaming
        username: postgres
        password: postgres
        max-pool-size: 20
  server:
    base-url : http://localhost:8085
    http:
      port: 8085
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  health:
      checks:
        data-source-health-check:
          jndi-name: jdbc/uploaderDS
        disk-space-health-check:
          threshold: 50000000
        etcd-health-check:
          connection-url: http://192.168.99.100:2379/health

service:
  os: windows
  files_path: C:\Users\maja\Documents\RSO\projekt\Uploader\files\