apiVersion: apps/v1
kind: Deployment
metadata:
  name: uploader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uploader
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
      - image: mu2729/streaming-uploader
        name: uploader
        env:
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_SERVER_HTTP_PORT
          value: "8080"
        - name: KUMULUZEE_SERVER_BASE-URL
          value: http://159.122.186.127:30497
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://uploader-db:5432/streaming
        - name: KUMULUZEE_HEALTH_CHECKS_ETCDHEALTHCHECK_CONNECTIONURL
          value: http://etcd:2379/health
        - name: SERVICE_OS
          value: linux
        - name: SERVICE_FILES_PATH
          value: /files/
        ports:
        - containerPort: 8080
          protocol: TCP
          name: uploader-port
        livenessProbe:
          httpGet:
            path: /health
            port: uploader-port
          initialDelaySeconds: 30
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: uploader
spec:
  type: NodePort
  selector:
      app: uploader
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8080